CREATE TABLE USER (
    UserID VARCHAR(36) PRIMARY KEY,
    Email VARCHAR(255) UNIQUE NOT NULL CHECK (Email LIKE '%@cit.edu'),
    Password VARCHAR(255) NOT NULL,
    UserType ENUM('Student', 'Officer', 'Admin', 'Guest') NOT NULL
);

CREATE TABLE ORGANIZATION (
    OrgID VARCHAR(20) PRIMARY KEY,
    OrgName VARCHAR(255) NOT NULL,
    Category VARCHAR(100) NOT NULL,
    DateEstablished DATE NOT NULL
);

CREATE TABLE STUDENT (
    UserID VARCHAR(36) PRIMARY KEY,
    StudentID VARCHAR(20) UNIQUE NOT NULL,
    FullName VARCHAR(255) NOT NULL,
    Course VARCHAR(100) NOT NULL,
    YearLevel VARCHAR(50) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE
);

CREATE TABLE OFFICER (
    UserID VARCHAR(36) PRIMARY KEY,
    OrgID VARCHAR(20) NOT NULL,
    Position VARCHAR(100) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE,
    FOREIGN KEY (OrgID) REFERENCES ORGANIZATION(OrgID) ON DELETE CASCADE
);

CREATE TABLE MEMBERSHIP (
    MembershipID VARCHAR(50) PRIMARY KEY,
    StudentUserID VARCHAR(36) NOT NULL,
    OrgID VARCHAR(20) NOT NULL,
    Status ENUM('Pending', 'Approved') DEFAULT 'Pending' NOT NULL,
    FOREIGN KEY (StudentUserID) REFERENCES STUDENT(UserID) ON DELETE CASCADE,
    FOREIGN KEY (OrgID) REFERENCES ORGANIZATION(OrgID) ON DELETE CASCADE
);

CREATE TABLE EVENT (
    EventID VARCHAR(50) PRIMARY KEY,
    OrgID VARCHAR(20) NOT NULL,
    EventTitle VARCHAR(255) NOT NULL,
    Date DATE NOT NULL,
    Venue VARCHAR(255) NOT NULL,
    FOREIGN KEY (OrgID) REFERENCES ORGANIZATION(OrgID) ON DELETE CASCADE
);

CREATE TABLE ATTENDANCE (
    AttendanceID VARCHAR(50) PRIMARY KEY,
    MembershipID VARCHAR(50) NOT NULL,
    EventID VARCHAR(50) NOT NULL,
    CheckInTime DATETIME NOT NULL,
    FOREIGN KEY (MembershipID) REFERENCES MEMBERSHIP(MembershipID) ON DELETE CASCADE,
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID) ON DELETE RESTRICT
);